### ISSUE TITLE
Hasil Perncarian

### ISSUE THREAD

**Issue by dindrabastari** [ilyashrn/sambilkerja#1]
Hasil perncarian dari setiap kata kunci yang di cari selalu error, muncul notif error di file 
content/job-list.php
line ke 18
![search result image](https://cloud.githubusercontent.com/assets/17075115/13033662/f453ed40-d351-11e5-9281-9762d0a30bb0.PNG)

**Comment by ilyashrn** [comment]
Done ya
![screen shot 2016-02-15 at 9 27 22 pm](https://cloud.githubusercontent.com/assets/13843296/13051290/f0323a4e-d42a-11e5-946c-73d44e3d8006.png)
