### ISSUE TITLE
[Perusahaan] List Pekerjaan yang didaftarin ga muncul

### ISSUE THREAD

**Issue by dindrabastari** [ilyashrn/sambilkerja#11]
![list-pendaftar-kerja](https://cloud.githubusercontent.com/assets/17075115/13688323/b33f6d78-e753-11e5-9837-a7d388196c27.png)

**Comment by ilyashrn** [comment]
Ini juga muncul kok, coba databasenya diupdate juga. 
![screen shot 2016-03-11 at 10 02 01 am](https://cloud.githubusercontent.com/assets/13843296/13692032/5d6efd42-e770-11e5-8bc3-08538379d9d7.png)
