### ISSUE TITLE
[Admin/Worker Profile] List lowongan pekerjaan yang pernah diambil gamuncul

### ISSUE THREAD

**Issue by dindrabastari** [ilyashrn/sambilkerja#13]
![list-pekerjaan-admin](https://cloud.githubusercontent.com/assets/17075115/13688354/f42613dc-e753-11e5-84b6-11d338cd3ec5.png)

**Comment by ilyashrn** [comment]
Same here

**Comment by ilyashrn** [comment]
![Uploading Screen Shot 2016-03-11 at 10.03.18 AM.png…]()

**Comment by ilyashrn** [comment]
![screen shot 2016-03-11 at 10 03 18 am](https://cloud.githubusercontent.com/assets/13843296/13692054/8fed553e-e770-11e5-8087-7f9b0ad2915b.png)
