### ISSUE TITLE
[Admin/Worker Profile] Information Detail Error

### ISSUE THREAD

**Issue by dindrabastari** [ilyashrn/sambilkerja#14]
![worker-profile](https://cloud.githubusercontent.com/assets/17075115/13688367/05ca3884-e754-11e5-91b3-52316b9d5f69.png)

**Comment by ilyashrn** [comment]
tidak error disini 
![screen shot 2016-03-11 at 10 12 45 am](https://cloud.githubusercontent.com/assets/13843296/13692185/d4972402-e771-11e5-8d9f-6b33e5d066a7.png)
