### ISSUE TITLE
Tahun lulus pada saat menambahkan Riwayat Pendidikan

### ISSUE THREAD

**Issue by dindrabastari** [ilyashrn/sambilkerja#2]
Kalo misalnya si pekerja masih kuliah kan gabisa masukin yang tahun lulusnya, nah itu gaada notif apa apa kalo tahun lulus di kosongin, trus hasilnya jadi '**2013-0000**', hal yang sama juga di riwayat pekerjaan, di ganti jadi '**2013-Sekarang**', gitu aja

Pas nambahin riwayat pendidikan :
![riwayat pendidikan - input](https://cloud.githubusercontent.com/assets/17075115/13033690/b337ba34-d352-11e5-8307-2a5d6d9d7cc8.PNG)

Hasilnya :
![riwayat pendidikan - result](https://cloud.githubusercontent.com/assets/17075115/13033691/bd5c9782-d352-11e5-82ee-1c53afe3cbf6.PNG)

**Comment by ilyashrn** [comment]
Done juga ya
![screen shot 2016-02-15 at 10 29 07 pm](https://cloud.githubusercontent.com/assets/13843296/13052826/93e78358-d433-11e5-8f4c-bf2d4ec8418d.png)
